// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/node_modules/**',
      '**/coverage/**',
      // electron-builder's packaged output and pwa-scanner's file://-loadable
      // build — neither matches the generic dist/build ignores above.
      'apps/pwa-scanner/dist-electron/**',
      'apps/electron/release/**',
      // Capacitor's generated native Gradle/Java/Kotlin project — not our
      // source, regenerated by `npx cap sync`/`npx cap add android`.
      'apps/android/android/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  {
    // Electron's main/preload processes are plain CommonJS (require/module,
    // not the ESM "type": "module" the rest of the repo uses), and run
    // under Node with its own globals rather than a bundler.
    files: ['apps/electron/src/**/*.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
    rules: {
      // CommonJS is the deliberate choice here (see apps/electron/src/main.js
      // comment) — not something to migrate off require()/module.exports for.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
);
